### ISSUE TITLE
Illustrate broadcasting over wavenumber grids (or wavenumber PencilArray) in `gradient.jl` ? 

### ISSUE THREAD

**Issue by glwagner** [jipolanco/PencilFFTs.jl#42]
In the `gradient.jl` example, a gradient is computed via FFTs by multiplying a transformed field by a wavenumber vector and then transforming back to physical space.

The multiplication between the wavenumbers and the transformed field is by looping over indices

https://github.com/jipolanco/PencilFFTs.jl/blob/4e0cdfe19f73473d48a9bd2132217d15e468b90c/docs/examples/gradient.jl#L140-L154

I'm wondering if it might make sense to illustrate how this computation might be done with broadcasting syntax? Broadcasting might preferred in some applications: it's more compact, and generalizes (in principle...) to GPU.

Partly I'm motivated to propose this modification because I'd like to use this syntax but don't understand quite how to achieve it! I see that 

https://github.com/jipolanco/PencilFFTs.jl/blob/4e0cdfe19f73473d48a9bd2132217d15e468b90c/examples/gradient.jl#L258

is used in

https://github.com/jipolanco/PencilFFTs.jl/blob/4e0cdfe19f73473d48a9bd2132217d15e468b90c/examples/gradient.jl#L133-L138

and might illustrate how `localgrid` abstracts the notion of three "coordinates" (basically, three arrays with size `(Nx, 1, 1)`, `(1, Ny, 1)`, and `(1, 1, Nz)`... ?)

An alternative might use broadcasting with wavenumbers wrapped in a PencilArray. Not sure which is preferred (is `localgrid` just a wrapper for 3 "special" PencilArray with dimensions as above?)

Thanks for the super useful package btw!

**Comment by glwagner** [comment]
@johnryantaylor @simone-silvestri might be interested too

**Comment by jipolanco** [comment]
Right, so `localgrid` was introduced quite recently (https://github.com/jipolanco/PencilArrays.jl/pull/45) precisely to be able to broadcast `PencilArray`s with coordinates / wavenumbers in an efficient manner. So this is the recommended way of doing this kind of broadcasting.

> I'm wondering if it might make sense to illustrate how this computation might be done with broadcasting syntax? Broadcasting might preferred in some applications: it's more compact, and generalizes (in principle...) to GPU.

Maybe I'm misunderstanding the question, but this is precisely what ["Method 4"](https://jipolanco.github.io/PencilFFTs.jl/dev/generated/gradient/#gradient_method_broadcast) illustrates. Perhaps it should appear first, as it's by far the simplest implementation. It's just that this wasn't possible until quite recently...

This is also illustrated in the [PencilArrays docs](https://jipolanco.github.io/PencilArrays.jl/dev/LocalGrids/#Using-local-grids) (but maybe this is not that easy to find?).

> and might illustrate how `localgrid` abstracts the notion of three "coordinates" (basically, three arrays with size `(Nx, 1, 1)`, `(1, Ny, 1)`, and `(1, 1, Nz)`... ?)

Yeah, that's precisely the way one should think about `localgrid`.

> An alternative might use broadcasting with wavenumbers wrapped in a PencilArray. Not sure which is preferred (is localgrid just a wrapper for 3 "special" PencilArray with dimensions as above?)

The problem is that one cannot construct a 1D `PencilArray` over a 3D geometry, because that would be incompatible with the domain partitioning scheme (how does one partition a 1D array?). Maybe there is a clever way to somehow allow this, but for now it's not possible. In any case, that's what `localgrid` is for.

Alternatively, one could create a full 3D array of wavenumbers (with e.g. `u[i, j, k] = kx[i] * ky[j] * kz[k]`) and broadcast with that, and that would be totally fine, except that it's a bit wasteful as it allocates a whole array (but, once again, that might be totally fine for some use cases).

**Comment by jipolanco** [comment]
> I think what I'm proposing is to partition three 3D PencilArray that have singleton dimensions, but maybe this doesn't make sense.

I see, that should be possible, and could be added if there's an interest (but I guess `localgrid` already solves part of the need for that).

> Ah, indeed! However, that example doesn't use "provided" coordinates but rather generates x, y, z under the hood, I suppose.

The coordinates are provided [further above](https://jipolanco.github.io/PencilArrays.jl/dev/LocalGrids/#Creating-local-grids) :)

It's the same as in the gradient example really, only that here we're using the `grid.x`, `grid.y`, `grid.z` syntax (instead of `grid[1]`, `grid[2]`, `grid[3]`) to extract the coordinates. Note that the `x`, `y` and `z` names are hardcoded (this was inspired by a recent [StaticArrays](https://github.com/JuliaArrays/StaticArrays.jl/pull/980) change). I guess all of this should be clarified in the docs...

**Comment by glwagner** [comment]
> The coordinates are provided [further above](https://jipolanco.github.io/PencilArrays.jl/dev/LocalGrids/#Creating-local-grids) :)

Wow, you're right, I missed it again...

**Comment by glwagner** [comment]
Anyways since broadcasting is actually in the `gradient.jl` example I'll close this.
